### ISSUE TITLE
Bump required max version of elm-css

### ISSUE THREAD

**Issue by maxekman** [scottcorgan/elm-css-normalize#1]
First of all, great to find this port of Normalize.css!

However, is it possible to bump the required max versions to reflect the state of the current dependencies? I'm using elm-css 6.1.0 but the max version as a dep for this package is 5.0.0.

**Comment by scottcorgan** [comment]
Totally. Want to open a quick PR?

**Comment by maxekman** [comment]
Sure, will try to submit one later today.

**Comment by maxekman** [comment]
PR submitted, hope you don't mind the other changes to make this package more useable in projects.
