### ISSUE TITLE
Error: I cannot find a set of packages that works with your constraints.

### ISSUE THREAD

**Issue by groteck** [scottcorgan/elm-css-normalize#9]
I'm a noob on Elm, but looks like when a new version of the elm-css package is on the `elm-package.json`  the installation command doesn't work (`elm-package install scottcorgan/elm-css-normalize`)

```bash
⇒  elm-package install                              
Error: I cannot find a set of packages that works with your constraints.

One way to rebuild your constraints is to clear everything out of the
"dependencies" field of elm-package.json and add them back one at a time with
`elm-package install`.

I hope to automate this in the future, but at least there is a way to make
progress for now!
````

**Comment by scottcorgan** [comment]
Do you want to send a PR? I'd be happy to merge it in and publish 👍

**Comment by groteck** [comment]
I thinlk is already solved in this commit https://github.com/scottcorgan/elm-css-normalize/pull/7/commits/3a950e917e679d9205d8d6e032e3980de0744b29

**Comment by groteck** [comment]
scottcorgan
